### PR TITLE
feat: cluster visualization draw_clusters.py (by Chao)

### PR DESCRIPTION
**Pull request by wdconinc**
### Briefly, what does this PR introduce?
Work by @Chao1009, originally at https://github.com/eic/EICrecon/pull/494.

Add a script to visualize clusters and hits for an event.

### What kind of change does this PR introduce?
- [ ] Bug fix (issue #__)
- [ ] New feature (issue https://github.com/eic/EICrecon/issues/493)
- [ ] Documentation update
- [ ] Other: __

### Please check if this PR fulfills the following:
- [ ] Tests for the changes have been added
- [ ] Documentation has been added / updated
- [ ] Changes have been communicated to collaborators

### Does this PR introduce breaking changes? What changes might users need to make to their code?
No, it's a tool.

### Does this PR change default behavior?
No, it's a tool.

### CODE REVIEW

**Review by ruse-traveler — APPROVED** [review]
LGTM!

BTW you should be able to push changes without going through a PR!

**Comment by wdconinc** [comment]
> BTW you should be able to push changes without going through a PR!

Force of habit.

**Comment by wdconinc** [comment]
Or need for external validation.

**Comment by wdconinc** [comment]
I'll bring it up to my therapist.

**Pull request merged**
