### PR TITLE
add Tracking/particle_track_parameters.C

### PR DESCRIPTION
**Pull request by veprbl**
This is a snippet to demonstrate use of https://github.com/eic/EICrecon/pull/1210 (depends on that PR).

### CODE REVIEW

**Comment by veprbl** [comment]
Upstream PR merged yesterday.

**Review by ruse-traveler — APPROVED** [review]
LGTM

(BTW I think you should be able to push without going through a PR ⏫)

**Comment by veprbl** [comment]
Sure, I can push/self-merge, if you prefer.

**Comment by ruse-traveler** [comment]
Definitely! Since this should be a place for "non-critical" code, push/self-merge will work well!

(You also won't have to wait on me to finally notice that there's a PR waiting to merge 😓)

**Pull request merged**
